execute_parser:
  dblp_path: "artifacts/dblp.xml"
  save_path: "artifacts"
  batch: 1000000
  log_path: "logs"

split:
  read_path: "artifacts/dblp.csv"
  rows_each: 100000
  output_path: "artifacts/split"

combine:
  read_path: "artifacts/split"
  output_path: "artifacts/batch"

sample:
  read_path: "artifacts"
  filename: "dblp.csv"
  output_path: "artifacts"
  sample_frac: 0.05 # frac between 0 and 1
  