execute_parser:
  dblp_path: "artifacts/dblp.xml"
  save_path: "artifacts"
  batch: 1000000
  log_path: "logs"

split:
  read_path: "artifacts/dblp.csv"
  rows_each: 100000
  output_path: "artifacts/split"

combine:
  read_path: "artifacts/split"
  output_path: "artifacts"

generate:
  read_path: "artifacts/dblp.csv"
  author_output_path: "artifacts/author.csv"
  publication_output_path: "artifacts/publication.csv"
  publish_output_path: "artifacts/publish.csv"

sample:
  read_path: "artifacts"
  filename: "dblp.csv"
  output_path: "artifacts"
  sample_frac: 0.01 # frac between 0 and 1
  
